### PR TITLE
Main folder deleted

### PR DESCRIPTION
**Pull request by Tmakinde**
I deleted the main folder of the repo because it preventing deployment on heroku.
it's preventing heroku from pointing the Procfile and index.php for proper deployment

### CODE REVIEW

**Review by Tolexvinny — COMMENTED** [review]
Awesome

**Review by Tolexvinny — COMMENTED** [review]
Weldone sir.

**Review by odeyale2016 — DISMISSED** [review]

**Review by Dawlz — DISMISSED** [review]

**Review by solomonconah — DISMISSED** [review]
Reviewed

**Comment by Tolexvinny** [comment]
👍

**Review by odeyale2016 — DISMISSED** [review]

**Review by solomonconah — DISMISSED** [review]

**Review by Dawlz — APPROVED** [review]

**Review by Dawlz — APPROVED** [review]

**Review by Dawlz — APPROVED** [review]

**Review by Dawlz — DISMISSED** [review]

**Review by Tolexvinny — APPROVED** [review]
You r doing well bro..

**Review by oagbeja — DISMISSED** [review]
Great job

**Review by Tolexvinny — COMMENTED** [review]
👍

**Review by Tolexvinny — DISMISSED** [review]

**Review by Tolexvinny — DISMISSED** [review]
Is okay, no problem.

**Review by odeyale2016 — APPROVED** [review]
Welldone

**Review by Tolexvinny — APPROVED** [review]
Good stuff

**Review by oagbeja — APPROVED** [review]
Great job

**Pull request merged**
