### PR TITLE
Post farmer username to database

### PR DESCRIPTION
**Pull request by Tmakinde**
I have created a route and a function in farmersConctroller to save farmer facebook username to database.

Also i added a profile to make a laravel pushable to heroku

### CODE REVIEW

**Review by Tolexvinny — COMMENTED** [review]
Good stuff Teemak 👍

**Review by Tolexvinny — APPROVED** [review]
Good stuff Teemak 👍

**Review by Tolexvinny — CHANGES_REQUESTED** [review]
Good stuff Teemak 👍

**Review by Tolexvinny — CHANGES_REQUESTED** [review]
Good stuff Teemak 👍

**Review by Tolexvinny — APPROVED** [review]

**Review by Tolexvinny — DISMISSED** [review]

**Comment by solomonconah** [comment]
Great

**Comment by Tolexvinny** [comment]
Nice one!

**Review by Tolexvinny — APPROVED** [review]
Cheers

**Review by Tolexvinny — APPROVED** [review]

**Review by oagbeja — APPROVED** [review]
Nice Work.

**Review by odeyale2016 — APPROVED** [review]
Nice one

**Review by odeyale2016 — APPROVED** [review]
Nice one

**Pull request merged**
